### ISSUE TITLE
gotoState does not call exitedState with passed arguments

### ISSUE THREAD

**Issue by davisdude** [kikito/stateful.lua#3]
I was reading through the spec when I noticed [this](https://github.com/kikito/stateful.lua/blob/d3c73101e72c4192870b581a01d452d015fb8b98/spec/unit_spec.lua#L103) test. When looking at the code for `:gotoState` I don't see it calling the `:exitedState` callback anywhere (except for `:popAllStates`, but that doesn't take the varargs).

It appears as if the functionality was added in [this](https://github.com/kikito/stateful.lua/commit/ada968bd0c39c56bbb16d185ea89f1eb9eebb6fe#diff-1ff81a827998a83782a3e9c86a5e86f4L138) commit and removed in [this](https://github.com/kikito/stateful.lua/commit/a037e9bfb28487d97e73efc094b9b84ba9a640e3#diff-1ff81a827998a83782a3e9c86a5e86f4L138) commit. It makes sense that the error has not been reported by busted because there are no states being popped, so `:exitedState` is not being called.

**Comment by davisdude** [comment]
Figured I'd tack this one on as well since it's pretty minor:
[Here](https://github.com/kikito/stateful.lua/blob/d3c73101e72c4192870b581a01d452d015fb8b98/spec/unit_spec.lua#L150) the variable `Pushed` is used instead of `Piled`

**Comment by kikito** [comment]
Hi, I just pushed a fix for this. Could you please test it to see if it works ok now? If so, I will release a new version of stateful.lua.

Thanks!

**Comment by davisdude** [comment]
Looks good to me
